export const SHOPLIST_REQUEST = "SHOPLIST_REQUEST";
export const SHOPLIST_SUCCESS = "SHOPLIST_SUCCESS";
export const SHOPLIST_FILTER = "SHOPLIST_FILTER";
export const SHOPLIST_AREA_AND_CATEGORY = "SHOPLIST_AREA_AND_CATEGORY";
